# Generated by Django 2.2.7 on 2019-12-27 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='software_man',
            name='software_ID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='music.software'),
            preserve_default=False,
        ),
    ]
