from django.urls import path

from . import views
urlpatterns = [
    path('', views.login),
    path('login/action', views.login_action, name='login_action'),
    path('register/', views.register, name='register'),
    path('register/action', views.register_action, name='register_action'),
    path('inputUserAccount', views.input_useraccount, name='input_user_account'),
    path('inputUserAccount/action', views.input_useraccount_action, name='input_user_account_action'),
    path('inputUserAccount/retrievePassword', views.retrieve_password, name='retrieve_password'),
    path('mainpage/', views.mainpage, name='mainpage'),
    path('softwareMainpage/', views.software_mainpage, name='software_mainpage'),
    path('softwareMainpage/softwareSongs', views.software_songs, name='software_songs'),
    path('softwareMainpage/softwareSongs/button', views.button, name='button'),
    path('softwareMainpage/softwareSongs/change', views.song_change, name='song_change'),
    path('softwareMainpage/softwareSongs/change/action', views.song_change_action, name='song_change_action'),
    path('softwareMainpage/softwareSongs/addSongs', views.add_songs, name='add_songs'),
    path('softwareMainpage/softwareSongs/addSongs/action', views.add_songs_action, name='add_songs_action'),
    path('softwareMainpage/softwareSongs/addMusician', views.add_musician, name='add_musician'),
    path('softwareMainpage/softwareSongs/addMusician/action', views.add_musician_action, name='add_musician_action'),
    path('softwareMainpage/personalInformation', views.software_personal_information, name='software_personal_information'),
    path('mainpage/STOP', views.STOP, name='mainpage_STOP'),
    path('mainpage/CTOP', views.CTOP, name='mainpage_CTOP'),
    path('mainpage/BestSinger', views.Best_singer, name='mainpage_Best_Singer'),
    path('mainpage/BestLyricsMaker', views.Best_lyrics_maker, name='mainpage_Best_lyrics_maker'),
    path('mainpage/BestComposer', views.Best_composer, name='mainpage_Best_composer'),
    path('mainpage/BestSoftware', views.Best_software, name='mainpage_Best_software'),
    path('mainpage/collection', views.collection, name="mainpage_collection"),
    path('mainpage/collection/delete', views.delete_my_collection, name='collection_delete'),
    path('mainpage/personalInformation', views.personalInformation, name='mainpage_personalInformation'),
    path('mainpage/personalInformation/modification', views.informationModification, name='information_modification'),
    path('mainpage/personalInformation/modification/action', views.informationModification_action,
         name='information_modification_action'),
    path('mainpage/personalInformation/passwordModification', views.change_password, name='password_modification'),
    path('mainpage/personalInformation/passwordModification/action', views.change_password_actiom,
         name='password_modification_action'),

    path('mainpage/query', views.query, name='mainpage_query'),
    path('mainpage/query/interlinkage', views.interlinkage, name='query_interlinkage'),
    path('mainpage/songList', views.song_list_view, name='song_list'),
    path('mainpage/songList/list', views.song_list, name='list'),
    path('inputUserAccount/retrievePassword/resetPassword', views.input_double_password, name='input_double_password'),
    path('inputUserAccount/retrievePassword/resetPassword/action', views.forget_password_action, name='reset_password')
]
